apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-react-ui
spec:
  selector:
    app: react-ui
  ports:
    - port: {{ .Values.reactui.service.port }}
      targetPort: {{ .Values.reactui.service.targetPort }}
  type: LoadBalancer
